version: '2.0'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - '3001:80'
    environment:
      - PORT=80
    networks:
      - my-network
  db:
    image: images.artifactory.dunnhumby.com/postgres:12
    #image: postgres:12
    environment:
      POSTGRES_DB: myweight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
